FROM nginx:1.27-alpine

EXPOSE 9090

COPY nginx.conf /etc/nginx/nginx.conf

COPY dist/ /usr/share/nginx/html

RUN sed -i -e 's/reload:8080/example.com/g' /etc/nginx/nginx.conf
RUN sed -i -e 's/server:8081/example.com/g' /etc/nginx/nginx.conf
